/*
 * This file is generated by jOOQ.
 */
package com.integration.socket.repository.jooq.tables;


import com.integration.socket.repository.jooq.DefaultSchema;
import com.integration.socket.repository.jooq.Indexes;
import com.integration.socket.repository.jooq.Keys;
import com.integration.socket.repository.jooq.tables.records.RankRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Rank extends TableImpl<RankRecord> {

    private static final long serialVersionUID = -875711850;

    /**
     * The reference instance of <code>rank</code>
     */
    public static final Rank RANK = new Rank();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RankRecord> getRecordType() {
        return RankRecord.class;
    }

    /**
     * The column <code>rank.id</code>.
     */
    public final TableField<RankRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>rank.rank</code>.
     */
    public final TableField<RankRecord, Integer> RANK_ = createField("rank", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>rank.score</code>.
     */
    public final TableField<RankRecord, Integer> SCORE = createField("score", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>rank.user_id</code>.
     */
    public final TableField<RankRecord, String> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>rank.username</code>.
     */
    public final TableField<RankRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>rank.game_type</code>.
     */
    public final TableField<RankRecord, Integer> GAME_TYPE = createField("game_type", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>rank.create_time</code>.
     */
    public final TableField<RankRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>rank</code> table reference
     */
    public Rank() {
        this(DSL.name("rank"), null);
    }

    /**
     * Create an aliased <code>rank</code> table reference
     */
    public Rank(String alias) {
        this(DSL.name(alias), RANK);
    }

    /**
     * Create an aliased <code>rank</code> table reference
     */
    public Rank(Name alias) {
        this(alias, RANK);
    }

    private Rank(Name alias, Table<RankRecord> aliased) {
        this(alias, aliased, null);
    }

    private Rank(Name alias, Table<RankRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Rank(Table<O> child, ForeignKey<O, RankRecord> key) {
        super(child, key, RANK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.RANK_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RankRecord, Integer> getIdentity() {
        return Keys.IDENTITY_RANK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RankRecord> getPrimaryKey() {
        return Keys.KEY_RANK_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RankRecord>> getKeys() {
        return Arrays.<UniqueKey<RankRecord>>asList(Keys.KEY_RANK_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Rank as(String alias) {
        return new Rank(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Rank as(Name alias) {
        return new Rank(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Rank rename(String name) {
        return new Rank(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Rank rename(Name name) {
        return new Rank(name, null);
    }
}
