/*
 * This file is generated by jOOQ.
 */
package com.integration.socket.repository.jooq;


import com.integration.socket.repository.jooq.tables.Map;
import com.integration.socket.repository.jooq.tables.RankBoard;
import com.integration.socket.repository.jooq.tables.User;
import com.integration.socket.repository.jooq.tables.records.MapRecord;
import com.integration.socket.repository.jooq.tables.records.RankBoardRecord;
import com.integration.socket.repository.jooq.tables.records.UserRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<RankBoardRecord, Integer> IDENTITY_RANK_BOARD = Identities0.IDENTITY_RANK_BOARD;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MapRecord> KEY_MAP_PRIMARY = UniqueKeys0.KEY_MAP_PRIMARY;
    public static final UniqueKey<MapRecord> KEY_MAP_NAME_UNIQUE = UniqueKeys0.KEY_MAP_NAME_UNIQUE;
    public static final UniqueKey<RankBoardRecord> KEY_RANK_BOARD_PRIMARY = UniqueKeys0.KEY_RANK_BOARD_PRIMARY;
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<RankBoardRecord, Integer> IDENTITY_RANK_BOARD = Internal.createIdentity(RankBoard.RANK_BOARD, RankBoard.RANK_BOARD.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<MapRecord> KEY_MAP_PRIMARY = Internal.createUniqueKey(Map.MAP, "KEY_map_PRIMARY", Map.MAP.NAME);
        public static final UniqueKey<MapRecord> KEY_MAP_NAME_UNIQUE = Internal.createUniqueKey(Map.MAP, "KEY_map_name_UNIQUE", Map.MAP.NAME);
        public static final UniqueKey<RankBoardRecord> KEY_RANK_BOARD_PRIMARY = Internal.createUniqueKey(RankBoard.RANK_BOARD, "KEY_rank_board_PRIMARY", RankBoard.RANK_BOARD.ID);
        public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = Internal.createUniqueKey(User.USER, "KEY_user_PRIMARY", User.USER.USER_ID);
    }
}
