/*
 * This file is generated by jOOQ.
 */
package com.integration.socket.repository.jooq.tables.records;


import com.integration.socket.repository.jooq.tables.RankBoard;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RankBoardRecord extends UpdatableRecordImpl<RankBoardRecord> implements Record7<Integer, Integer, Integer, String, String, Integer, Timestamp> {

    private static final long serialVersionUID = 528012561;

    /**
     * Setter for <code>rank_board.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>rank_board.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>rank_board.rank</code>.
     */
    public void setRank(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>rank_board.rank</code>.
     */
    public Integer getRank() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>rank_board.score</code>.
     */
    public void setScore(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>rank_board.score</code>.
     */
    public Integer getScore() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>rank_board.user_id</code>.
     */
    public void setUserId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>rank_board.user_id</code>.
     */
    public String getUserId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>rank_board.username</code>.
     */
    public void setUsername(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>rank_board.username</code>.
     */
    public String getUsername() {
        return (String) get(4);
    }

    /**
     * Setter for <code>rank_board.game_type</code>.
     */
    public void setGameType(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>rank_board.game_type</code>.
     */
    public Integer getGameType() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>rank_board.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>rank_board.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, String, String, Integer, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, String, String, Integer, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return RankBoard.RANK_BOARD.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return RankBoard.RANK_BOARD.RANK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return RankBoard.RANK_BOARD.SCORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return RankBoard.RANK_BOARD.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return RankBoard.RANK_BOARD.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return RankBoard.RANK_BOARD.GAME_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return RankBoard.RANK_BOARD.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getRank();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getGameType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getRank();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getGameType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RankBoardRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RankBoardRecord value2(Integer value) {
        setRank(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RankBoardRecord value3(Integer value) {
        setScore(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RankBoardRecord value4(String value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RankBoardRecord value5(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RankBoardRecord value6(Integer value) {
        setGameType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RankBoardRecord value7(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RankBoardRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, Integer value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RankBoardRecord
     */
    public RankBoardRecord() {
        super(RankBoard.RANK_BOARD);
    }

    /**
     * Create a detached, initialised RankBoardRecord
     */
    public RankBoardRecord(Integer id, Integer rank, Integer score, String userId, String username, Integer gameType, Timestamp createTime) {
        super(RankBoard.RANK_BOARD);

        set(0, id);
        set(1, rank);
        set(2, score);
        set(3, userId);
        set(4, username);
        set(5, gameType);
        set(6, createTime);
    }
}
